<template>
  <div class="container mt-4">
    <h1>Dataset</h1>

    <table class="table table-striped" id="doc-list">
      <thead>
        <tr>
          <th @click="sortBy('author')" style="cursor:pointer">
            <span style="font-weight:bold">Author</span>
            <span v-if="sortKey === 'author' && sortOrder === 1"> &#9650;</span>
            <span v-if="sortKey === 'author' && sortOrder === -1"> &#9660;</span>
          </th>
          <th @click="sortBy('title')" style="cursor:pointer">
            <span style="font-weight:bold">Title</span>
            <span v-if="sortKey === 'title' && sortOrder === 1"> &#9650;</span>
            <span v-if="sortKey === 'title' && sortOrder === -1"> &#9660;</span>
          </th>
          <th @click="sortBy('year')" style="cursor:pointer">
            <span style="font-weight:bold">Year</span>
            <span v-if="sortKey === 'year' && sortOrder === 1"> &#9650;</span>
            <span v-if="sortKey === 'year' && sortOrder === -1"> &#9660;</span>
          </th>
          <th>&nbsp;</th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(row, i) in sortedRows" :key="i">
          <td>{{ row.author }}</td>
          <td>{{ row.title }}</td>
          <td>{{ row.year }}</td>
          <td><a :href="row.txt">TXT</a></td>
          <td><a :href="row.pdf">PDF</a></td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script>
export default {
  data() {
    return {
      sortKey: 'title',
      sortOrder: 1,
      rows: [
      { author: 'Francis Haskins Eyles Stiles', title: 'An account of an eruption of Vesuvius', year: '1760', txt: 'https://corvo.matita.net/data-static-txt/BIBV_369_1762_EylesStiles_in_inglese_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/369_1762-EylesStiles_in inglese.pdf' },
      { author: 'Francis Haskins Eyles Stiles', title: 'Another account of the same eruption of Mount Vesuvius', year: '1760', txt: 'https://corvo.matita.net/data-static-txt/BIBV_370_1762_EylesStiles_in_inglese_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/370_1762-EylesStiles_in inglese.pdf' },
      { author: 'Marie-Louise Arconati Visconti', title: 'Appunti sull\'eruzione del Vesuvio del 1867-68', year: '1868', txt: 'https://corvo.matita.net/data-static-txt/BIBV_94_1872_ArconatiVisconti_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/94_1872-ArconatiVisconti.pdf' },
      { author: 'Ciro Saverio Minervino', title: 'Articolo di Lettera', year: '1779', txt: 'https://corvo.matita.net/data-static-txt/OV_pre1830_IDENT_LIBRO_728_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-pre1830./IDENT LIBRO 728.pdf' },
      { author: 'Giulio Cesare Recupito', title: 'Avviso dell\'incendio del Vesuvio', year: '1635', txt: 'https://corvo.matita.net/data-static-txt/BIBV_877_1635_Recupito_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/877_1635-Recupito.pdf' },
      { author: 'Anonymous', title: 'Breve catalogo di alcuni prodotti ritrovati nell\'ultima eruzione del Vesuvio', year: '1794', txt: 'https://corvo.matita.net/data-static-txt/OV_pre1830_IDENT_LIBRO_3102b_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-pre1830./IDENT LIBRO 3102b.pdf' },
      { author: 'Cristoforo Imperato', title: 'Breve descrizione del Monte Vesuvio e della diversità dè nomi di esso', year: '', txt: 'https://corvo.matita.net/data-static-txt/OV_post1830_IDENT_LIBRO_536_manoscritto_converted_compressed_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-post1830./IDENT LIBRO 536_manoscritto - converted_compressed.pdf' },
      { author: 'G.M. Olivieri', title: 'Breve descrizione istorico-fisica dell\'eruzione del Vesuvio avvenuta il dì 15 giugno 1794', year: '1794', txt: 'https://corvo.matita.net/data-static-txt/Microfiches_0719_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/Microfiches/0719.pdf' },
      { author: 'Eliseo Danza', title: 'Breve discorso dell\'incendio succeduto à 16 di Dicembre 1631', year: '1632', txt: 'https://corvo.matita.net/data-static-txt/35mm_Foglio_1_1631_Danza_35mm.txt', pdf: 'https://corvo.matita.net/data-static-pdf/35mm/Foglio 1_1631_Danza_35mm.pdf' },
      { author: 'Camillo Volpe', title: 'Breve discorso dell\'incendio succeduto à 16 di Dicembre 1631 nel Monte Vesuvio e luoghi convicini', year: '1632', txt: 'https://corvo.matita.net/data-static-txt/35mm_Foglio_14_1631_Volpe_35mm.txt', pdf: 'https://corvo.matita.net/data-static-pdf/35mm/Foglio 14_1631_Volpe_35mm.pdf' },
      { author: 'Henry James Johnston-Lavis', title: 'Breve e conciso rendiconto dei fenomeni eruttivi e della geologia del Monte Somma e del Vesuvio', year: '1891', txt: 'https://corvo.matita.net/data-static-txt/BIBV_465_1891_HJJohnstonLavis_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/465_1891-HJJohnstonLavis.pdf' },
      { author: 'Domenico Tata', title: 'Breve relazione dell\'ultima eruttazione del Vesuvio', year: '1790', txt: 'https://corvo.matita.net/data-static-txt/OV_pre1830_IDENT_LIBRO_1354_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-pre1830./IDENT LIBRO 1354.pdf' },
      { author: 'Francesco Del Giudice', title: 'Brevi considerazioni attorno ad alcuni più costanti fenomeni vesuviani', year: '1861', txt: 'https://corvo.matita.net/data-static-txt/BIBV_3134_1855_AAVV_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/3134_1855-AAVV.pdf' },
      { author: 'Ferdinando Galiani', title: 'Catalogo delle materie appartenenti al Vesuvio contenute nel Museo con alcune brevi osservazioni', year: '1772', txt: 'https://corvo.matita.net/data-static-txt/OV_pre1830_IDENT_LIBRO_3457_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-pre1830./IDENT&nbsp;&nbsp;LIBRO 3457.pdf' },
      { author: 'Anonymous', title: 'Cenno storico dell\'eruzione del Vesuvio avvenuta in ottobre dell\'anno 1822', year: '1822', txt: 'https://corvo.matita.net/data-static-txt/OV_pre1830_IDENT_LIBRO_85_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-pre1830./IDENT LIBRO 85.pdf' },
      { author: 'Carlo Siniscalco', title: 'Compendio delle principali eruzioni vesuviane dall\'anno 79 EV  infino alla descrizione delle recenti', year: '1863', txt: 'https://corvo.matita.net/data-static-txt/BIBV_1345_1863_Siniscalco_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/1345_1863-Siniscalco.pdf' },
      { author: 'Alberto Tarino', title: 'Comtinuazione dè successi del prossimo incendio del Vesuvio con gli effetti della cenere, e pietre da quello vomitate ...', year: '1661', txt: 'https://corvo.matita.net/data-static-txt/35mm_Foglio_L_Tarino_1660_35mm.txt', pdf: 'https://corvo.matita.net/data-static-pdf/35mm/Foglio L_Tarino_1660_35mm.pdf' },
      { author: 'Giuseppe Imbò', title: 'Considérations relevées de l\'étude séismique du dernier paroxysme vésuvien', year: '1954', txt: 'https://corvo.matita.net/data-static-txt/art_Imbo_sisimica_1944_in_francese_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/art/Imbo_sisimica 1944 in francese.pdf' },
      { author: 'Giuseppe Imbò', title: 'Considerazioni sulla presente attività del Vesuvio', year: '1949', txt: 'https://corvo.matita.net/data-static-txt/art_Imbo_BF02596785_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/art/Imbo_BF02596785.pdf' },
      { author: 'Gioacchino Zorda', title: 'Continuazione de fenomeni del Vesuvio dopo l\'eruzione del 1806 sino al principio della primavera 1810', year: '1810', txt: 'https://corvo.matita.net/data-static-txt/OV_pre1830_IDENT_LIBRO_1084_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-pre1830./IDENT LIBRO 1084.pdf' },
      { author: 'AAVV', title: 'Continuazione delle notizie riguardanti il Vesuvio', year: '1799', txt: 'https://corvo.matita.net/data-static-txt/BIBV_1089_1779_AAVV_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/1089_1779-AAVV.pdf' },
      { author: 'Simone Giros', title: 'Continuazione delle notizie riguardanti il Vesuvio', year: '1795', txt: 'https://corvo.matita.net/data-static-txt/BIBV_444_1795_Giros_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/444_1795-Giros.pdf' },
      { author: 'Domenico Tata', title: 'Continuazione delle notizie riguardanti il Vesuvio', year: '1795', txt: 'https://corvo.matita.net/data-static-txt/BIBV_81_1795_Anonymous_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/81_1795-Anonymous.pdf' },
      { author: 'Giuseppe Maria Mecatti', title: 'Continuazione delle oservazioni sopra diverse eruzioni del Vesuvio', year: '1761', txt: 'https://corvo.matita.net/data-static-txt/OV_pre1830_IDENT_LIBRO_647_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-pre1830./IDENT LIBRO 647.pdf' },
      { author: 'Ioannis Baptistae Masculi', title: 'De incendio Vesuvii excitato XVII Kal Januar anno trigesimo primo saeculi Decimiseptimi', year: '1633', txt: 'https://corvo.matita.net/data-static-txt/Microfiches_0634_in_latino_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/Microfiches/0634_in latino.pdf' },
      { author: 'Ambrogio Leone', title: 'De Nola Opuscolum Liber I, II, III', year: '1514', txt: 'https://corvo.matita.net/data-static-txt/BIBV_1226_1514_Leonis_in_latino_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/1226_1514-Leonis_in latino.pdf' },
      { author: 'Fabii Barberii', title: 'De Prognostico Cínerum, quos Vesuvius Mons, dum conflagrabatur eructavít', year: '1632', txt: 'https://corvo.matita.net/data-static-txt/BIBV_110_1632_Barbieri_in_latino_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/110_1632-Barbieri_in latino.pdf' },
      { author: 'Ioanni Dominico De Arminio', title: 'De terremotibus et incendiis eorumque causis et signis naturalibus, et supranaturalibus item de flagratione Vesuvii', year: '1632', txt: 'https://corvo.matita.net/data-static-txt/35mm_Foglio_5_1631_De_Arminio_35mm_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/35mm/Foglio 5_1631_De Arminio_35mm .pdf' },
      { author: 'Iulio Caesare Recupito', title: 'De Vesuviano incendio nuntius', year: '1632', txt: 'https://corvo.matita.net/data-static-txt/Microfiches_0875_in_latino_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/Microfiches/0875_in latino.pdf' },
      { author: 'Giovanni Targioni Tozzetti', title: 'Dei Monti Ignivomi della Toscana e del Vesuvio', year: '1779', txt: 'https://corvo.matita.net/data-static-txt/OV_pre1830_IDENT_LIBRO_3096_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-pre1830./IDENT LIBRO 3096.pdf' },
      { author: 'Giovanni Orlandi', title: 'Dell\'incendio del Monte di Somma compita relazionee di quanto è succeduto dino ad hoggi', year: '1631', txt: 'https://corvo.matita.net/data-static-txt/Microfiches_0722_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/Microfiches/0722.pdf' },
      { author: 'Giulio Cesare Braccini', title: 'Dell\'incendio fattosi nel Vesuvio a XVI di Dicembre MDCXXXI e delle sue cause ed effetti', year: '1632', txt: 'https://corvo.matita.net/data-static-txt/35mm_Foglio_2_3_1631_Braccini1632_35mm_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/35mm/Foglio 2-3_1631_Braccini1632_35mm.pdf' },
      { author: 'Luigi D\'Emilio', title: 'Della Conflagrazione vesuviana del 26 aprile 1872', year: '1873', txt: 'https://corvo.matita.net/data-static-txt/BIBV_335_1873_DEmilio_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/335_1873-DEmilio.pdf' },
      { author: 'Michele Attumonelli', title: 'Della eruzione del Vesuvio accaduta nel mese di agosto dell\'anno MDCCLXXIX', year: '1779', txt: 'https://corvo.matita.net/data-static-txt/BIBV_8_1779_Attumonelli_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/8_1779-Attumonelli.pdf' },
      { author: 'Albert Helm', title: 'Der ausbruch des Vesuv in april 1872', year: '1873', txt: 'https://corvo.matita.net/data-static-txt/OV_post1830_IDENT_LIBRO_488_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-post1830./IDENT LIBRO 488.pdf' },
      { author: 'Luigi Palmieri', title: 'Der ausbruch des Vesuv von 26 Aapril 1872', year: '1872', txt: 'https://corvo.matita.net/data-static-txt/OV_post1830_IDENT_LIBRO_733_in_tedesco_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-post1830./IDENT LIBRO 733_in tedesco.pdf' },
      { author: 'G. von Rath', title: 'Der Vesuv am 1 und 17 April 1871', year: '1871', txt: 'https://corvo.matita.net/data-static-txt/OV_post1830_IDENT_LIBRO_869_in_tedesco_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-post1830./IDENT LIBRO 869_in tedesco.pdf' },
      { author: 'Domenico Tata', title: 'Descrizione del grande incendio del Vesuvio successo nel giorno otto del mese di Agosto del corrente anno 1779', year: '1779', txt: 'https://corvo.matita.net/data-static-txt/OV_pre1830_IDENT_LIBRO_3102c_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-pre1830./IDENT LIBRO 3102c.pdf' },
      { author: 'Anonymous', title: 'Descrizione dell\'ultima eruzione del monte Vesuvio', year: '1768', txt: 'https://corvo.matita.net/data-static-txt/BIBV_69_1768_Anonymous_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/69_1768-Anonymous.pdf' },
      { author: 'Giuseppe Maria Mecatti', title: 'Descrizione della lava sacorsa nel mese di luglio 1754 nel cratere ossia piattaforma del Vesuvio, ed eruttata dalla cima d\'una montagnola', year: '1754', txt: 'https://corvo.matita.net/data-static-txt/Microfiches_0644_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/Microfiches/0644.pdf' },
      { author: 'Andrea Pigonati', title: 'Descrizione delle ultime eruzioni del Monte Vesuvio da\' 25 marzo 1766 fino al 10 dicembre dell\'anno medesimo', year: '1767', txt: 'https://corvo.matita.net/data-static-txt/BIBV_777_1767_Pigonati_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/777_1767-Pigonati.pdf' },
      { author: 'Giuseppe Maria Mecatti', title: 'Discorsi storici-filosofici sopra il Vesuvio Estratti .. Ai quali discorsi dsi sono aggiunte', year: '1754', txt: 'https://corvo.matita.net/data-static-txt/OV_pre1830_IDENT_LIBRO_645_compressed_converted_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-pre1830./IDENT. LIBRO 645_compressed - converted.pdf' },
      { author: 'Scipione Falcone', title: 'Discorso naturale delle cause et effetti causati nell\'incendio del Monte Vesevo, con relazione del tutto', year: '1632', txt: 'https://corvo.matita.net/data-static-txt/35mm_Foglio_7_8_1631_Falcone_35mm.txt', pdf: 'https://corvo.matita.net/data-static-pdf/35mm/Foglio 7-8_1631_Falcone_35mm.pdf' },
      { author: 'Biagio Sotis', title: 'Dissertazione fisico-chimica dell\'ultima eruzione vesuviana dè12 Agosto 1804, in cui si espongono dè tentativi per una spiega dè fenomeni in essa accaduti', year: '1804', txt: 'https://corvo.matita.net/data-static-txt/OV_pre1830_IDEN_LIBRO_1019_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-pre1830./IDEN LIBRO 1019.pdf' },
      { author: 'Giorgio Carafa', title: 'Dissertazione istorico-fisica delle cause e degli effetti dell\'eruttazioni del Monte Vesuvio negli anni 1751, e 1752', year: '1752', txt: 'https://corvo.matita.net/data-static-txt/BIBV_176_1752_Carafa_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/176_1752-Carafa.pdf' },
      { author: 'Anonymous', title: 'Distinta relazione de portentosi effetti cagionati dalla meravigliosa eruzione fatta dal Monte Vesuvio  detto di Somma', year: '1694', txt: 'https://corvo.matita.net/data-static-txt/Microfiches_1093_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/Microfiches/1093.pdf' },
      { author: 'Gaetano D\'Amato', title: 'Divisamento critico sulle correnti opinioni intorno a fenomeni del Vesuvio e degli altri vulcani', year: '1756', txt: 'https://corvo.matita.net/data-static-txt/Microfiches_0236_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/Microfiches/0236.pdf' },
      { author: 'Anonymous', title: 'Due lettere di Plinio il Giovane A Tacito .. A proposito dell\'ultima eruzione dè 15 giugno 1794', year: '1794', txt: 'https://corvo.matita.net/data-static-txt/OV_pre1830_IDENT_LIBRO_3112_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-pre1830./IDENT LIBRO 3112.pdf' },
      { author: 'Ivan de Quinones', title: 'El Monte Vesuvio aora la montagna de Soma', year: '1632', txt: 'https://corvo.matita.net/data-static-txt/BIBV_337_1632_DeQuinones_in_spagnolo_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/337_1632-DeQuinones_in spagnolo.pdf' },
      { author: 'Giuseppe Imbò', title: 'Energies éruptives pendant le paroxysme du Vesuve du mars 1944', year: '1955', txt: 'https://corvo.matita.net/data-static-txt/art_Imbo_BF02595979_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/art/Imbo_BF02595979.pdf' },
      { author: 'Giordano', title: 'Eruzione del Vesuvio del giorno 8 dicembre 1859', year: '1859', txt: 'https://corvo.matita.net/data-static-txt/BIBV_441_1862_Giordano_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/441_1862-Giordano.pdf' },
      { author: 'Giovanni Guarini, Luigi Plamieri, Arcangelo Scacchi', title: 'Eruzioni Vesuviane del 1850 e 1855', year: '1855', txt: 'https://corvo.matita.net/data-static-txt/BIBV_458_1855_GuariniPalmieriScacchi_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/458_1855-GuariniPalmieriScacchi.pdf' },
      { author: 'Teodoro Monticelli?', title: 'Escursioni fatte sul Vesuvio in compagnia d\'illustri soggetti, e celebri dotti stranieri dal 1817 al 1820', year: '', txt: 'https://corvo.matita.net/data-static-txt/OV_post1830_IDENT_LIBRI_3307_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-post1830./IDENT LIBRI 3307.pdf' },
      { author: 'Domenico De Tommasi', title: 'Esperienze ed osservazioni del sale ammoniaco vesuviano', year: '1794', txt: 'https://corvo.matita.net/data-static-txt/OV_pre1830_IDENT_LIBRO_3103_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-pre1830./IDENT LIBRO 3103.pdf' },
      { author: 'Edw Berkeley', title: 'Extract of a Letter of Mr. Edw Berkeley from Naples', year: '1719', txt: 'https://corvo.matita.net/data-static-txt/BIBV_118_1717_Berkeley_in_inglese_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/118_1717-Berkeley_in inglese.pdf' },
      { author: 'Alessandro Malladra', title: 'Grotta di scolamento lavico negli efflussi vesuviani del 1858', year: '1917', txt: 'https://corvo.matita.net/data-static-txt/16mm_microfilm_0007_Parte8_compressed.txt', pdf: 'https://corvo.matita.net/data-static-pdf/16mm/microfilm 0007_Parte8_compressed.pdf' },
      { author: 'Stephanus Vinandum Pighius', title: 'Hercules Prodicius sev principis iuventutis vita et peregrinatio', year: '1587', txt: 'https://corvo.matita.net/data-static-txt/OV_pre1830_ident_libro_1361_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-pre1830./ident libro 1361.pdf' },
      { author: 'Henry Le Hon', title: 'Histoire complete de la grande eruption du Vesuve de 1631', year: '1866', txt: 'https://corvo.matita.net/data-static-txt/BIBV_3271_1866_LeHon_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/3271_1866-LeHon.pdf' },
      { author: 'Angelo De Eugenii', title: 'Il maraviglioso e tremendo incendio del Monte Vesuvio, detto a Napoli la Montagna di Somma del 1631', year: '1631', txt: 'https://corvo.matita.net/data-static-txt/Microfiches_0368_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/Microfiches/0368.pdf' },
      { author: 'Frate Angelo De Eugenii da Perugia', title: 'Il meraviglioso e tremendo incendio del Monte Vesuvio, detto a Napoli la Montagna di Somma nel 1631', year: '1631', txt: 'https://corvo.matita.net/data-static-txt/35mm_Foglio_1_1631_Frat_Angelo_De_Eugenii_35mm.txt', pdf: 'https://corvo.matita.net/data-static-pdf/35mm/Foglio 1_1631_Frat\'Angelo De Eugenii_35mm.pdf' },
      { author: 'Ottorino De Fiore', title: 'Il periodo eruttivo iniziatosi al Vesuvio nel 1913', year: '1915', txt: 'https://corvo.matita.net/data-static-txt/BIBV_265_1915_DeFiore_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/265_1915-DeFiore.pdf' },
      { author: 'Cesare Monitio', title: 'Il Vesbo Furioso overo incendio del Monte di Somma sotto perpetua metafora', year: '1647', txt: 'https://corvo.matita.net/data-static-txt/OV_pre1830_ident_libro_288a_export_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-pre1830./ident libro 288a_export.pdf' },
      { author: 'AAVV', title: 'Il Vesuvio - Strenna pel 1869', year: '1879', txt: 'https://corvo.matita.net/data-static-txt/BIBV_10_1869_AAVV_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/10_1869-AAVV.pdf' },
      { author: 'Marciano Di Leo', title: 'Il Vesuvio nell\'ultima eruzione degli 8 agosto 1779 - canto', year: '1779', txt: 'https://corvo.matita.net/data-static-txt/BIBV_348_1779_DiLeo_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/348_1779-DiLeo.pdf' },
      { author: 'Gregorio Carafa', title: 'In opusculum de novissima Vesuvii conflagratione - Epistola isagogica', year: '1632', txt: 'https://corvo.matita.net/data-static-txt/Microfiches_0175_in_latino_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/Microfiches/0175_in latino.pdf' },
      { author: 'Giovanni Maria Della Torre', title: 'Incendio del Vesuvio accaduto li 19 d\'ottobre del 1767', year: '1767', txt: 'https://corvo.matita.net/data-static-txt/BIBV_299_1767_DellaTorre_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/299_1767-DellaTorre.pdf' },
      { author: 'Giovanni Maria Della Torre', title: 'Incendio trentesimo del Vesuvio accaduto gli 8 agosto 1779', year: '1779', txt: 'https://corvo.matita.net/data-static-txt/BIBV_303_1779_DellaTorre_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/303_1779-DellaTorre.pdf' },
      { author: 'Accademia Pontiana', title: 'Intorno all\'incendio del Vesuvio del dì 8 dicembre 1861', year: '1862', txt: 'https://corvo.matita.net/data-static-txt/OV_post1830_IDENT_LIBRO_1086_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-post1830./IDENT LIBRO 1086.pdf' },
      { author: 'Ignazio Sorrentino', title: 'Istoria del Monte Vesuvio divisata in due libri', year: '1734', txt: 'https://corvo.matita.net/data-static-txt/BIBV_1020_1734_Sorrentino_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/1020_1734-Sorrentino.pdf' },
      { author: 'Carlo Siniscalco', title: 'Istoria del Vesuvio e del Monte di Somma con la descrizione delle principali eruzioni vesuviane dall\'anno 79EV fino alle recenti', year: '1890', txt: 'https://corvo.matita.net/data-static-txt/BIBV_1343_1890_Siniscalco_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/1343_1890-Siniscalco.pdf' },
      { author: 'Francesco Serao', title: 'Istoria dell\'incendio accaduto nel mese di maggio dell\'anno 1737 - Seconda edizione riveduta ed accresciuta di alquante annotazioni', year: '1740', txt: 'https://corvo.matita.net/data-static-txt/BIBV_1151_1740_Serao_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/1151_1740-Serao.pdf' },
      { author: 'Francesco Serao', title: 'Istoria dell\'incendio del Vesuvio accaduto nel mese di maggio dell\'anno 1737 - Prima edizione', year: '1738', txt: 'https://corvo.matita.net/data-static-txt/BIBV_972_1737_Serao_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/972_1737-Serao.pdf' },
      { author: 'Francesco Serao', title: 'Istoria dell\'incendio del Vesuvio accaduto nell\'anno 1737-Seconda Edizione', year: '1740', txt: 'https://corvo.matita.net/data-static-txt/OV_pre1830_IDENT_LIBRO_3362_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-pre1830./IDENT LIBRO 3362.pdf' },
      { author: 'Gaetano De Bottis', title: 'Istoria di vari incendi del Monte Vesuvio cui si aggiunge una breve relazione di un fulmine', year: '1786', txt: 'https://corvo.matita.net/data-static-txt/Microfiches_0034_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/Microfiches/0034.pdf' },
      { author: 'Gaspare Paragallo', title: 'Istoria naturale del Monte Vesuvio divisata in due libri', year: '1705', txt: 'https://corvo.matita.net/data-static-txt/BIBV_1286_1705_Paragallo_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/1286_1705-Paragallo.pdf' },
      { author: 'Lorenzo Casertano', title: 'L\'azione del vento su proietti vesuviani durante il parossismo del marzo 1944', year: '1950', txt: 'https://corvo.matita.net/data-static-txt/art_Casertano_1949_L_azione_del_vento_converted_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/art/Casertano (1949) . - L\'azione del vento.. - converted.pdf' },
      { author: 'Ph. Glangeaud', title: 'L\'eruption du Vesuve en avril 1906', year: '1907', txt: 'https://corvo.matita.net/data-static-txt/BIBV_447_1907_Glangeaud_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/447_1907-Glangeaud.pdf' },
      { author: 'Anonymous', title: 'L\'eruzione del Vesuvio nella notte de\' 15 giugno 1794', year: '', txt: 'https://corvo.matita.net/data-static-txt/BIBV_75_1794_Anonymous_CFT_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/75_1794-Anonymous CFT.pdf' },
      { author: 'Gioseffo Mormile Napoletano', title: 'L\'incendi del Monte Vesuvio e delle staggi e rovine che ha fatto nè tempi antichi e moderni infino a 3 di marzo 1632', year: '1632', txt: 'https://corvo.matita.net/data-static-txt/35mm_Foglio_16_17_1631_Mormile_35mm.txt', pdf: 'https://corvo.matita.net/data-static-pdf/35mm/Foglio 16-17_1631_Mormile_35mm.pdf' },
      { author: 'Giuseppe Imbò', title: 'L\'Osservatorio Vesuviano e le sue vicende durante il periodo bellico (1940 - 1945)', year: '1949', txt: 'https://corvo.matita.net/data-static-txt/art_Imbo_1949_converted_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/art/Imbo(1949) converted.pdf' },
      { author: 'Francesco Giordani', title: 'La configurazione del cratere Vesuviano prima del recente crollo del cono avventizio', year: '1916', txt: 'https://corvo.matita.net/data-static-txt/BIBV_439_1916_Giordani_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/439_1916-Giordani.pdf' },
      { author: 'Fr. De Rosa', title: 'La flora vesuviana e l\'eruzione dell\'aprile 1906', year: '1907', txt: 'https://corvo.matita.net/data-static-txt/BIBV_343_1907_DeRosa_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/343_1907-DeRosa.pdf' },
      { author: 'Anonymous', title: 'La miracolosa immagine di Nostra Signora del Carmine della Torre del Greco', year: '1711', txt: 'https://corvo.matita.net/data-static-txt/OV_pre1830_IDENT_LIBRO_3359_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-pre1830./IDENT LIBRO 3359.pdf' },
      { author: 'Nicolo Maria Oliva', title: 'La ristampata lettera con aggiunta di molte cose notabili', year: '1632', txt: 'https://corvo.matita.net/data-static-txt/Microfiches_0718_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/Microfiches/0718.pdf' },
      { author: 'Francesco De Ambrosio', title: 'La Torre del Greco', year: '1862', txt: 'https://corvo.matita.net/data-static-txt/BIBV_1147_1861_DeAmbrosio_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/1147_1861-DeAmbrosio.pdf' },
      { author: 'Sebastiano Orlandi', title: 'La tregua senza fede del Vesuvio', year: '1632', txt: 'https://corvo.matita.net/data-static-txt/35mm_Foglio_66_Orlandi_1631_35mm.txt', pdf: 'https://corvo.matita.net/data-static-pdf/35mm/Foglio 66_Orlandi_1631_35mm.pdf' },
      { author: 'Antonio Scherillo', title: 'Le lave e le scorie dell\'eruzione vesuviana del marzo 1944', year: '1949', txt: 'https://corvo.matita.net/data-static-txt/art_Scherillo_1949_Le_lave_e_le_scorie_converted_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/art/Scherillo (1949) - Le lave e le scorie converted.pdf' },
      { author: 'Giuseppe Imbò', title: 'Le recenti manifestazioni eruttive vesuviane', year: '1948', txt: 'https://corvo.matita.net/data-static-txt/art_Imbo_1948_riassunto_1944_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/art/Imbo 1948 riassunto 1944.pdf' },
      { author: 'Antonio Scherillo', title: 'Le ricerche petrografiche sui prodotti attuali del Vesuvio compiute nell\'istituto di Mineralogia dell\' Università di Napoli', year: '1950', txt: 'https://corvo.matita.net/data-static-txt/art_Scherillo_BF02596079_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/art/Scherillo_BF02596079.pdf' },
      { author: 'Michele Arcangelo D\'Onofrio', title: 'Lettera ad un amico di provincia sul terremoto accaduto a 26 luglio a seguito della eruzione vesuviana del 12 agosto del corrente anno 1805', year: '1805', txt: 'https://corvo.matita.net/data-static-txt/BIBV_359_1805_DOnofrio_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/359_1805-DOnofrio.pdf' },
      { author: 'Alessando De Humboldt', title: 'Lettera al Cav. Monticelli', year: '', txt: 'https://corvo.matita.net/data-static-txt/OV_post1830_IDENT_LIBRI_3309_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-post1830./IDENT LIBRI 3309.pdf' },
      { author: 'Alessandro Cattani', title: 'Lettera critico-filosofica se della vesuviana eruttazione accaduta nel 1767 ai 19 di Ottobre', year: '1768', txt: 'https://corvo.matita.net/data-static-txt/BIBV_188_1768_Cattani_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/188_1768-Cattani.pdf' },
      { author: 'Antonio Di Gennaro', title: 'Lettera del signore don Andtonio Di Gennaro Duca di Belfort Scritta al Sig. Cristofano Amaduzzi in data di Napoli a Mergellina', year: '1779', txt: 'https://corvo.matita.net/data-static-txt/OV_pre1830_IDENT_LIBRO_3502_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-pre1830./IDENT LIBRO 3502.pdf' },
      { author: 'Caneva Eremita SS.Salvatore', title: 'Lettera dell\'eremita del SS. Salvatore', year: '1794', txt: 'https://corvo.matita.net/data-static-txt/BIBV_169_1794_Caneva_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/169_1794-Caneva.pdf' },
      { author: 'Antonio Bulifon', title: 'Lettera nella quale si da distinto ragguagli dell\'incendio del Vesuvio succeduto nel mese di Aprile 1694', year: '1694', txt: 'https://corvo.matita.net/data-static-txt/BIBV_163_1694_Bulifon_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/163_1694-Bulifon.pdf' },
      { author: 'Ascanio Filomarino Duca della Torre', title: 'Lettera prima sull\'eruzione del Vesuvio del 15 giugno 1794', year: '1794', txt: 'https://corvo.matita.net/data-static-txt/BIBV_384_1794_Filomarino_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/384_1794-Filomarino.pdf' },
      { author: 'Ascanio Filomarino Duca della Torre', title: 'Lettera seconda sull\'eruzione del Vesuvio del 15 giugno 1794', year: '1794', txt: 'https://corvo.matita.net/data-static-txt/BIBV_385_1794_Filomarino_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/385_1794-Filomarino.pdf' },
      { author: 'Michele Ferrara', title: 'Lettera sull\'analisi della cenere del Monte Vesuvio eruttata nel dì 16-17-18 giugno 1794', year: '1794', txt: 'https://corvo.matita.net/data-static-txt/OV_pre1830_IDENT_LIBRO_380_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-pre1830./IDENT LIBRO 380.pdf' },
      { author: 'Iacouo Fenice', title: 'Lo struppio della montagna de Somma in rima napoletana', year: '1632', txt: 'https://corvo.matita.net/data-static-txt/BIBV_379_1632_Fenice_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/379_1632-Fenice.pdf' },
      { author: 'Anonymous', title: 'Los incendios de la montaña de soma', year: '1632', txt: 'https://corvo.matita.net/data-static-txt/BIBV_58_1632_Anonymous_in_spagnolo_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/58_1632-Anonymous_in spagnolo.pdf' },
      { author: 'Teodoro Monticelli', title: 'Memoria su le vicende del Vesuvio', year: '1827', txt: 'https://corvo.matita.net/data-static-txt/OV_post1830_IDENT_LIBRI_3311_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-post1830./IDENT LIBRI 3311.pdf' },
      { author: 'Scipione Breislak - Antonio Winspeare', title: 'Memoria sull\'eruzione del Vesuvio accaduta la sera dè 15 giugno 1794', year: '1794', txt: 'https://corvo.matita.net/data-static-txt/BIBV_147_1794_BreislakWinspeare_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/147_1794-BreislakWinspeare.pdf' },
      { author: 'Athanasii Kircheri', title: 'Mundus Subterraneus - libri XII', year: '1665', txt: 'https://corvo.matita.net/data-static-txt/Microfiches_0479_in_latino_compressed_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/Microfiches/0479_in latino_compressed.pdf' },
      { author: 'Pietro Adami', title: 'Napoli liberata dalle staggi del Vesuvio', year: '1633', txt: 'https://corvo.matita.net/data-static-txt/35mm_Foglio_17_1631_Adami_35mm.txt', pdf: 'https://corvo.matita.net/data-static-pdf/35mm/Foglio 17_1631_Adami_35mm.pdf' },
      { author: 'Giovanni Maria Della Torre', title: 'Narrazione del torrente di fuoco uscito dal Monte Vesuvio nell\'anno 1751', year: '1751', txt: 'https://corvo.matita.net/data-static-txt/BIBV_297_1751_DellaTorre_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/297_1751-DellaTorre.pdf' },
      { author: 'Alessandro Malladra', title: 'Nel Cratere del Vesuvio', year: '1914', txt: 'https://corvo.matita.net/data-static-txt/16mm_microfilm_0007_Parte5_compressed.txt', pdf: 'https://corvo.matita.net/data-static-pdf/16mm/microfilm 0007__Parte5_compressed.pdf' },
      { author: 'Carlo Siniscalco', title: 'Notizie del Vesuvio e del Monte di Somma, con la descrizione delle principali ..', year: '1881', txt: 'https://corvo.matita.net/data-static-txt/OV_post1830_IDENT_LIBRO_3080_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-post1830./IDENT LIBRO 3080.pdf' },
      { author: 'Giuseppe Mercalli', title: 'Notizie vesuviane', year: '1895', txt: 'https://corvo.matita.net/data-static-txt/BIBV_425_1893_Mercalli_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/425_1893-Mercalli.pdf' },
      { author: 'Vincenzo Bove', title: 'Nuove osservazioni fatte sopra gli effetti dell\'incendio del Monte Vesuvio - Aggiunte alla Decima Relatione dello stesso incendio ...', year: '1632', txt: 'https://corvo.matita.net/data-static-txt/35mm_Foglio_A_Bove_Aggiunte_1631_35mm_compressed.txt', pdf: 'https://corvo.matita.net/data-static-pdf/35mm/Foglio A_Bove_Aggiunte_1631_35mm_compressed.pdf' },
      { author: 'Luigi Riccio', title: 'Nuovi documenti sull\'incendio vesuviano dell\'anno 1631 e bibliografia di queslla eruzione', year: '1889', txt: 'https://corvo.matita.net/data-static-txt/OV_post1830_IDENT_LIBRO_1323_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-post1830./IDENT LIBRO 1323.pdf' },
      { author: 'Antonio Scherillo', title: 'Nuovo contributo allo studio dei prodotti dell\'eruzione vesuviana del 1944', year: '1950', txt: 'https://corvo.matita.net/data-static-txt/art_Scherillo_BF02596798_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/art/Scherillo_BF02596798.pdf' },
      { author: 'F.J.B. Menard de la Groye', title: 'Observations avec reflexions sur l\'etat et les phenomenes du Vesuve pendant une partie dels années 1813 et 1814', year: '1815', txt: 'https://corvo.matita.net/data-static-txt/BIBV_293_1815_DelaGroye_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/293_1815-DelaGroye.pdf' },
      { author: 'William Hamilton', title: 'Observations on Mount Vesuvius, Mount Etna, and other volcanoes in a series of letters addressed to the Royal Society 1774', year: '1774', txt: 'https://corvo.matita.net/data-static-txt/OV_pre1830_IDENT_LIBRO_1203_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-pre1830./IDENT LIBRO 1203.pdf' },
      { author: 'Teodoro Monticelli', title: 'Opere dell\'Abate Teodoro Monticelli', year: '1841', txt: 'https://corvo.matita.net/data-static-txt/BIBV_3308_1841_Monticelli_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/3308_1841-Monticelli.pdf' },
      { author: 'Giuseppe Maria Mecatti', title: 'Osservazioni che si son fatte nel Vesuvio nel mese di agosto 1752 fino a tutto il mese di luglio dell\'anno 1754', year: '1754', txt: 'https://corvo.matita.net/data-static-txt/BIBV_643_1754_Mecatti_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/643_1754-Mecatti.pdf' },
      { author: 'Federico Schiavoni', title: 'Osservazioni geodetiche sul Vesuvio', year: '1855', txt: 'https://corvo.matita.net/data-static-txt/OV_post1830_IDENT_LIBRO_3070_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-post1830./IDENT LIBRO 3070.pdf' },
      { author: 'Domenico Bartaloni', title: 'Osservazioni sopra il Vesuvio', year: '1774', txt: 'https://corvo.matita.net/data-static-txt/BIBV_111_1774_Bartaloni_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/111_1774-Bartaloni.pdf' },
      { author: 'Teodoro Monticelli', title: 'Osservazioni sullo stato del Vesuvio dal 1822 al 1829', year: '', txt: 'https://corvo.matita.net/data-static-txt/OV_post1830_IDENT_LIBRI_3315_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-post1830./IDENT LIBRI 3315.pdf' },
      { author: 'Giuseppe Imbò', title: 'Parossismo del 18-29 marzo 1944', year: '1949', txt: 'https://corvo.matita.net/data-static-txt/art_Imbo_Cap_V_Parossismo_del_18_29_marzo_1944_converted_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/art/Imbo - Cap.V Parossismo del 18-29 marzo 1944 - converted.pdf' },
      { author: 'AB (Galiani?)', title: 'Raccolta di Lettere scientifiche ed erudite dirette dall\'AB. ** a diversi suoi amici - Tomo I', year: '1780', txt: 'https://corvo.matita.net/data-static-txt/OV_pre1830_IDENT_LIBRO_72_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-pre1830./IDENT LIBRO 72.pdf' },
      { author: 'Giuseppe Maria Mecatti', title: 'Racconto storico-filosofico del Vesuvio e particolarmente di quanto è occorso in quest\'ultima eruzione principiata il dì 25 ottobre 1751', year: '1752', txt: 'https://corvo.matita.net/data-static-txt/BIBV_1248_1752_Mecatti_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/1248_1752-Mecatti.pdf' },
      { author: 'Antonio Barba', title: 'Ragionamento fisico-chimico sull\'eruzione ultima del Vesuvio accaduta a 15 giugno 1794', year: '1794', txt: 'https://corvo.matita.net/data-static-txt/Microfiches_0109_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/Microfiches/0109.pdf' },
      { author: 'Gaetano De Bottis', title: 'Ragionamento istorico dell\'incendio del Monte Vesuvio che cominciò nell\'anno 1770 e delle varie eruzioni che ha cagionato', year: '1776', txt: 'https://corvo.matita.net/data-static-txt/BIBV_1153_1776_DeBottis.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/1153_1776-DeBottis.pdf' },
      { author: 'Gaetano De Bottis', title: 'Ragionamento istorico intorno a\' nuovi vulcani comparsi alla fine dell\'anno scorso 1760 nel territorio della Torre del Greco', year: '1761', txt: 'https://corvo.matita.net/data-static-txt/BIBV_1152_1761_DeBottis_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/1152_1761-DeBottis.pdf' },
      { author: 'Gaetano De Bottis', title: 'Ragionamento istorico intorno all\'eruzione del Vesuvio che cominciò il 29 luglio dell\'anno 1779', year: '1779', txt: 'https://corvo.matita.net/data-static-txt/BIBV_1150_1779_DeBottis_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/1150_1779-DeBottis.pdf' },
      { author: 'Bernardo De Geronimo', title: 'Raguaglio del Vesuvio o pure epistole familiari', year: '1737', txt: 'https://corvo.matita.net/data-static-txt/OV_pre1830_ident_libro_288b_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-pre1830./ident libro 288b.pdf' },
      { author: 'Nicolao Angelo Eliseo', title: 'Rationalis Methodus curandi febres flagrante Vesevo subortas', year: '1645', txt: 'https://corvo.matita.net/data-static-txt/OV_pre1830_identificativo_libro_363_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-pre1830./identificativo libro 363.pdf' },
      { author: 'GIovan Domenico Pollera', title: 'Relatione dell\'incendio del Monte di Somma, successa nell\'anno 1631 ...', year: '1632', txt: 'https://corvo.matita.net/data-static-txt/35mm_Foglio_66_Pollera_1631_35mm_copia.txt', pdf: 'https://corvo.matita.net/data-static-pdf/35mm/Foglio 66_Pollera_1631_35mm copia.pdf' },
      { author: 'Arcangelo Scacchi', title: 'Relazione dell\'incendio accaduto nel Vesuvio nel mese di febbraio 1850', year: '1850', txt: 'https://corvo.matita.net/data-static-txt/OV_post1830_IDENT_LIBRO_958_V_2_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-post1830./IDENT LIBRO 958 V.2.pdf' },
      { author: 'Michele Torcia', title: 'Relazione dell\'ultima eruzione del Vesuvio accaduta nel mese di agosto di questo anno 1779', year: '1779', txt: 'https://corvo.matita.net/data-static-txt/BIBV_1048_1779_Torcia_in_Italiano_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/1048_1779-Torcia_in Italiano.pdf' },
      { author: 'S.A.T.', title: 'Relazione dell\'ultima eruzione del Vesuvio accaduta nel mese di agosto di questo anno, secondo le osservazioni del S.A.T.', year: '1787', txt: 'https://corvo.matita.net/data-static-txt/OV_pre1830_IDENT_LIBRO_1403_converted_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-pre1830./IDENT. LIBRO 1403 - converted.pdf' },
      { author: 'Domenico Tata', title: 'Relazione dell\'ultima eruzione del Vesuvio della sera dè 15 giugno', year: '1794', txt: 'https://corvo.matita.net/data-static-txt/OV_pre1830_IDENT_LIBRO_3102a_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-pre1830./IDENT LIBRO 3102a.pdf' },
      { author: 'Catalogo', title: 'Relazione dellultima eruzione del Vesuvio della sera de\' 15 giugno', year: '1794', txt: 'https://corvo.matita.net/data-static-txt/Microfiches_1355_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/Microfiches/1355.pdf' },
      { author: 'Ascanio Filomarino Duca della Torre', title: 'Relazione prima dell\'eruzione del Vesuvio dagli 11 agosto fino al 18 settembre 1804', year: '1804', txt: 'https://corvo.matita.net/data-static-txt/BIBV_390_1804_Filomarino_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/390_1804-Filomarino.pdf' },
      { author: 'Michele Arcangelo D\'Onofrio', title: 'Relazione ragionata della eruzione del nostro Vesuvio nel dì 15 giugno 1794', year: '1794', txt: 'https://corvo.matita.net/data-static-txt/BIBV_357_1794_DOnofrio_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/357_1794-DOnofrio.pdf' },
      { author: 'William Hamilton', title: 'Relazione ragionata della eruzione del Vesuvio di Napoli accaduta a\' 15 giugno 1794', year: '', txt: 'https://corvo.matita.net/data-static-txt/BIBV_74_1794_Anonymous_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/74_1794-Anonymous.pdf' },
      { author: 'Alessandro Malladra', title: 'Riassunto sull\'attività del Vesuvio per lìanno 1917', year: '1918', txt: 'https://corvo.matita.net/data-static-txt/16mm_microfilm_0007_Parte10_compressed.txt', pdf: 'https://corvo.matita.net/data-static-pdf/16mm/microfilm 0007_Parte10_compressed.pdf' },
      { author: 'Angelo Bellani', title: 'Salita al Vesuvio', year: '1835', txt: 'https://corvo.matita.net/data-static-txt/OV_post1830_IDENT_LIBRO_3374_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-post1830./IDENT LIBRO 3374.pdf' },
      { author: 'Urbano Giorgi', title: 'Scelta di poesie nell\'Incendio del Vesuvio', year: '1632', txt: 'https://corvo.matita.net/data-static-txt/OV_pre1830_idemt_libro_3467_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-pre1830./idemt. libro 3467.pdf' },
      { author: 'Antonio Parascandola', title: 'Se sia stato esclusivamente terminale l\'efflusso lavico nella eruzione vesuviana del marzo 1944', year: '1947', txt: 'https://corvo.matita.net/data-static-txt/art_Parascandola_1947_Se_sia_stato_esclusivamente_terminale_converted_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/art/Parascandola(1947) - Se sia stato esclusivamente terminale converted.pdf' },
      { author: 'Anonymous', title: 'Seconda lettera di un legista napolitano ad un suo fratello in provincia', year: '1794', txt: 'https://corvo.matita.net/data-static-txt/BIBV_1100_1794_Anonymous_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/1100_1794-Anonymous.pdf' },
      { author: 'Antonio Lazzari', title: 'Segnalazione della caduta in Albania delle ceneri del Vesuvio dell\'eruzione del marzo 1944', year: '1947', txt: 'https://corvo.matita.net/data-static-txt/art_Lazzari_1947_Segnalazione_della_caduta_converted_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/art/Lazzari(1947) - Segnalazione della caduta converted.pdf' },
      { author: 'Alessandro Malladra', title: 'Sopra l\'attività del Vesuvio nell\'Aprile 1917', year: '1917', txt: 'https://corvo.matita.net/data-static-txt/16mm_microfilm_0007_Parte9_compressed.txt', pdf: 'https://corvo.matita.net/data-static-pdf/16mm/microfilm 0007_Parte9_compressed.pdf' },
      { author: 'Leopoldo Pilla', title: 'Sopra la produzione delle fiamme né vulcani', year: '1844', txt: 'https://corvo.matita.net/data-static-txt/OV_post1830_IDENT_LIBRO_795_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-post1830./IDENT LIBRO 795.pdf' },
      { author: 'Teodoro Monticelli, Nicola Covelli', title: 'Storia de\' fenomeni del Vesuvio avvenuti negli anni 1821, 1822 e parte del 1823', year: '1823', txt: 'https://corvo.matita.net/data-static-txt/BIBV_686_1823_MonticelliCovelli_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/686_1823-MonticelliCovelli.pdf' },
      { author: 'Giovanni Maria Della Torre', title: 'Storia e fenomeni del Vesuivio esposti dalla sua origine fino al 1767', year: '1768', txt: 'https://corvo.matita.net/data-static-txt/BIBV_300_1768_DellaTorre_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/300_1768-DellaTorre.pdf' },
      { author: 'Giovanni Maria Della Torre', title: 'Storia e fenomeni del Vesuvio', year: '1755', txt: 'https://corvo.matita.net/data-static-txt/BIBV_298_1755_DellaTorre_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/298_1755-DellaTorre.pdf' },
      { author: 'Giuseppe Imbò', title: 'Studio termico di fumarole vesuviane', year: '1927', txt: 'https://corvo.matita.net/data-static-txt/art_BF02719518_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/art/BF02719518.pdf' },
      { author: 'Alessandro Malladra', title: 'Sui fenomeni consecutivi all\'apertura della bocca 5 luglio 1913', year: '1913', txt: 'https://corvo.matita.net/data-static-txt/16mm_microfilm_0007_Parte7_compressed.txt', pdf: 'https://corvo.matita.net/data-static-pdf/16mm/microfilm 0007_Parte7_compressed.pdf' },
      { author: 'Giuseppe Imbò', title: 'Sul dinamico riposo del Vesuvio', year: '1956', txt: 'https://corvo.matita.net/data-static-txt/art_Imbo_1956_Sul_dinamico_riposo_del_Vesuvio_converted_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/art/Imbo(1956) - Sul dinamico riposo del Vesuvio converted.pdf' },
      { author: 'Orazio Silvestri', title: 'Sulla eruzione del Vesuvio incominciata il 12 novembre 1867-Ricerche chimiche', year: '1868', txt: 'https://corvo.matita.net/data-static-txt/BIBV_1007_1867_Silvestri_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/1007_1867-Silvestri.pdf' },
      { author: 'Pasquale Franco', title: 'Sulle fiamme recentemente osservate al Vesuvio', year: '1899', txt: 'https://corvo.matita.net/data-static-txt/BIBV_403_1899_Franco_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/403_1899-Franco.pdf' },
      { author: 'Luigi Palmieri', title: 'The eruption of Vesuvius in 1872', year: '1873', txt: 'https://corvo.matita.net/data-static-txt/OV_post1830_IDENT_LIBRO_735_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-post1830./IDENT LIBRO 735.pdf' },
      { author: 'Henry James Johnston-Lavis', title: 'The geology of Monte Somma and Vesuvius, being a study in volcanology', year: '1884', txt: 'https://corvo.matita.net/data-static-txt/OV_post1830_IDENT_LIBRO_1221_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-post1830./IDENT LIBRO 1221.pdf' },
      { author: 'Gianbernardino Giuliani', title: 'Trattato del Vesuvio e dei suoi incendi', year: '1632', txt: 'https://corvo.matita.net/data-static-txt/BIBV_445_1632_Giuliani_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/445_1632-Giuliani.pdf' },
      { author: 'Agnello di Santa Maria dè Scalzi Agostiniani d\'Italia', title: 'Trattato scientifico delle cause che concorsero al fuoco, terremoto del Monte Vesuvio vicino Napoli', year: '1632', txt: 'https://corvo.matita.net/data-static-txt/35mm_Foglio_15_16_1631_Agnello_di_Santa_Maria_35mm.txt', pdf: 'https://corvo.matita.net/data-static-pdf/35mm/Foglio 15-16_1631_Agnello di Santa Maria_35mm.pdf' },
      { author: 'Giuseppe Maria Carusi', title: 'Tre passeggiate al Vesuvio nei dì 3 e 21 giugno e 27 settembre 1858', year: '1858', txt: 'https://corvo.matita.net/data-static-txt/BIBV_181_1858_Carusi_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/181_1858-Carusi.pdf' },
      { author: 'Anonymous', title: 'Vera relatione dell\'horribil caso et incendio occorso per l\'esalazione del Monte di Somma, detto Vessuvio, vicino alla città di Napoli', year: '', txt: 'https://corvo.matita.net/data-static-txt/35mm_Foglio_48_1631_Anonymous_35mm.txt', pdf: 'https://corvo.matita.net/data-static-pdf/35mm/Foglio 48_1631_Anonymous_35mm.pdf' },
      { author: 'Giacomo Milesio da Ponta Hibernese', title: 'Vera relazione del miserabile e memorabile caso successo nella falda dellla nominatissima Montagna di Somma altrimenti detta Mons Visuvii', year: '1631', txt: 'https://corvo.matita.net/data-static-txt/35mm_Foglio_49_1631_Milesio_35mm.txt', pdf: 'https://corvo.matita.net/data-static-pdf/35mm/Foglio 49_1631_Milesio_35mm.pdf' },
      { author: 'Simone Giros', title: 'Veridica relazione di Somone Giros giardiniere della real Villa Favorita circa l\'ultima eruzione del Vesuvio accaduta ai 15 giugno per tutto luglio 1794', year: '1794', txt: 'https://corvo.matita.net/data-static-txt/BIBV_443_1794_Giros_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/BIBV/443_1794-Giros.pdf' },
      { author: 'Donato Perillo', title: 'Vero e distinto ragguaglio di ciò che operossi dal Procurator Fiscale ..', year: '1755', txt: 'https://corvo.matita.net/data-static-txt/OV_pre1830_IDENT_LIBRO_67_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-pre1830./IDENT LIBRO 67.pdf' },
      { author: 'Francesco Brignone', title: 'Versi sulla eruzione vesuviana del 1872', year: '1872', txt: 'https://corvo.matita.net/data-static-txt/OV_post1830_IDENT_LIBRO_3392_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-post1830./IDENT LIBRO 3392.pdf' },
      { author: 'Angelo Pesce - Giuseppe Rolandi', title: 'Vesuvio 1944 - L\'ultima eruzione', year: '2000', txt: 'https://corvo.matita.net/data-static-txt/art_Rolandi_Vesuvio_1944_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/art/Rolandi_Vesuvio_1944.pdf' },
      { author: 'Vincentii Alsarii Crucii', title: 'Vesuvius ardens sive exercitatio medico-physica', year: '1632', txt: 'https://corvo.matita.net/data-static-txt/Microfiches_1405_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/Microfiches/1405.pdf' },
      { author: 'Louis Valentin', title: 'Voyage medical en Italie fait l\'année 1820, precedé d\'une excursion au volcan du Mont-Vesuve', year: '1822', txt: 'https://corvo.matita.net/data-static-txt/OV_post1830_IDENT_LIBRO_1056_pdf.txt', pdf: 'https://corvo.matita.net/data-static-pdf/OV-post1830./IDENT LIBRO 1056.pdf' },
    ],
    }
  },
  computed: {
    sortedRows() {
      return [...this.rows].sort((a, b) => {
        const va = a[this.sortKey] || ''
        const vb = b[this.sortKey] || ''
        if (this.sortKey === 'year') {
          return ((parseInt(va) || 0) - (parseInt(vb) || 0)) * this.sortOrder
        }
        return va.localeCompare(vb, undefined, { sensitivity: 'base' }) * this.sortOrder
      })
    },
  },
  methods: {
    sortBy(key) {
      if (this.sortKey === key) {
        this.sortOrder *= -1
      } else {
        this.sortKey = key
        this.sortOrder = 1
      }
    },
  },
}
</script>
